/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Allocation = IDL.Record({
  'id' : IDL.Nat,
  'resourceId' : IDL.Nat,
  'taskId' : IDL.Nat,
});
export const Request = IDL.Record({
  'id' : IDL.Nat,
  'resourceId' : IDL.Nat,
  'taskId' : IDL.Nat,
});
export const Resource = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'priority' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createAllocation' : IDL.Func([IDL.Nat, IDL.Nat], [Allocation], []),
  'createRequest' : IDL.Func([IDL.Nat, IDL.Nat], [Request], []),
  'createResource' : IDL.Func([IDL.Text], [Resource], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Nat], [Task], []),
  'deleteAllocation' : IDL.Func([IDL.Nat], [], []),
  'deleteRequest' : IDL.Func([IDL.Nat], [], []),
  'deleteResource' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllAllocations' : IDL.Func([], [IDL.Vec(Allocation)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTasksByPriority' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllocation' : IDL.Func([IDL.Nat], [Allocation], ['query']),
  'getRequest' : IDL.Func([IDL.Nat], [Request], ['query']),
  'getResource' : IDL.Func([IDL.Nat], [Resource], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Task], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Allocation = IDL.Record({
    'id' : IDL.Nat,
    'resourceId' : IDL.Nat,
    'taskId' : IDL.Nat,
  });
  const Request = IDL.Record({
    'id' : IDL.Nat,
    'resourceId' : IDL.Nat,
    'taskId' : IDL.Nat,
  });
  const Resource = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'priority' : IDL.Nat,
  });
  
  return IDL.Service({
    'createAllocation' : IDL.Func([IDL.Nat, IDL.Nat], [Allocation], []),
    'createRequest' : IDL.Func([IDL.Nat, IDL.Nat], [Request], []),
    'createResource' : IDL.Func([IDL.Text], [Resource], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Nat], [Task], []),
    'deleteAllocation' : IDL.Func([IDL.Nat], [], []),
    'deleteRequest' : IDL.Func([IDL.Nat], [], []),
    'deleteResource' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllAllocations' : IDL.Func([], [IDL.Vec(Allocation)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTasksByPriority' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllocation' : IDL.Func([IDL.Nat], [Allocation], ['query']),
    'getRequest' : IDL.Func([IDL.Nat], [Request], ['query']),
    'getResource' : IDL.Func([IDL.Nat], [Resource], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Task], []),
  });
};

export const init = ({ IDL }) => { return []; };