/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Allocation {
  'id' : bigint,
  'resourceId' : bigint,
  'taskId' : bigint,
}
export interface Request {
  'id' : bigint,
  'resourceId' : bigint,
  'taskId' : bigint,
}
export interface Resource { 'id' : bigint, 'name' : string }
export interface Task { 'id' : bigint, 'name' : string, 'priority' : bigint }
export interface _SERVICE {
  'createAllocation' : ActorMethod<[bigint, bigint], Allocation>,
  'createRequest' : ActorMethod<[bigint, bigint], Request>,
  'createResource' : ActorMethod<[string], Resource>,
  'createTask' : ActorMethod<[string, bigint], Task>,
  'deleteAllocation' : ActorMethod<[bigint], undefined>,
  'deleteRequest' : ActorMethod<[bigint], undefined>,
  'deleteResource' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllAllocations' : ActorMethod<[], Array<Allocation>>,
  'getAllRequests' : ActorMethod<[], Array<Request>>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTasksByPriority' : ActorMethod<[], Array<Task>>,
  'getAllocation' : ActorMethod<[bigint], Allocation>,
  'getRequest' : ActorMethod<[bigint], Request>,
  'getResource' : ActorMethod<[bigint], Resource>,
  'getTask' : ActorMethod<[bigint], Task>,
  'updateTask' : ActorMethod<[bigint, string, bigint], Task>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];